#FAZER benchs de escala 100  e só por ultimofazer esse aqui de 1 core (rodar o  run_novocompose.sh com o SCALE_FACTOR=100.0 e depois as queries de 10.0 e 1.0)

services:
  polars-benchmark-1c60g:
    build:
      context: .
      dockerfile: Dockerfile.ubuntu2204
    container_name: polars-benchmark-1c60g
    cpuset: "0"
    mem_limit: 60g

    volumes:
      - ./output:/root/polars-benchmark/output
      - ./data:/root/polars-benchmark/data

    environment:
      - SCALE_FACTOR=1.0
    networks:
      - python-network
    stdin_open: true
    tty: true
    
  polars-benchmark-8c60g:
    build:
      context: .
      dockerfile: Dockerfile.ubuntu2204
    container_name: polars-benchmark-8c60g
    cpuset: "0-7"
    mem_limit: 60g

    volumes:
      - ./output:/root/polars-benchmark/output
      - ./data:/root/polars-benchmark/data

    environment:
      - SCALE_FACTOR=1.0
    networks:
      - python-network
    stdin_open: true
    tty: true

  polars-benchmark-16c60g:
    build:
      context: .
      dockerfile: Dockerfile.ubuntu2204
    container_name: polars-benchmark-16c60g
    cpuset: "0-15"
    mem_limit: 60g

    volumes:
      - ./output:/root/polars-benchmark/output
      - ./data:/root/polars-benchmark/data

    environment:
      - SCALE_FACTOR=1.0
    networks:
      - python-network
    stdin_open: true
    tty: true

  polars-benchmark-32c60g:
    build:
      context: .
      dockerfile: Dockerfile.ubuntu2204
    container_name: polars-benchmark-32c60g
    cpuset: "0-31"
    mem_limit: 60g

    volumes:
      - ./output:/root/polars-benchmark/output
      - ./data:/root/polars-benchmark/data

    environment:
      - SCALE_FACTOR=1.0
    networks:
      - python-network
    stdin_open: true
    tty: true

networks:
  python-network:
    driver: bridge